### ISSUE TITLE
feat: get type of node (node/proposer/prover)

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-client#189]
Any possibility to fetch from the taiko node which type it is (node/proposer/prover)? I don't think we can right now but maybe this could be useful? Feel free to close this issue if you think otherwise :)

**Comment by davidtaikocha** [comment]
hmmm I don't think node can know whether a proposer / prover is connecting to it. Only the user who is running the prover / proposer clients can know that.
