### ISSUE TITLE
Bug: Failed to start Taiko client

### ISSUE THREAD

**Issue by wangtsiao** [taikoxyz/taiko-client#213]
Taiko-client failed to start, the error message is belowing.
```
CRIT [05-06|20:10:17.557] Failed to start Taiko client             error="abi: improperly encoded uint64 value"
```

After I searched for a while, I found that this error is caused by [autogenerated code](https://github.com/taikoxyz/taiko-client/blob/main/bindings/gen_taiko_l1.go#L527), which interacts with l1 contract.

**Comment by wangtsiao** [comment]
By the way, taiko-client [create client](https://github.com/taikoxyz/taiko-client/blob/main/pkg/rpc/client.go#L50) using [backoff](https://github.com/taikoxyz/taiko-client/blob/main/pkg/rpc/dial.go#L17) reconnection strategy, this definitely make the program more robust.

However, the implement lacks necessary logging when encountered network failed or execution server side err. The direct consequence of this, when configuration like `endpoints` are wrong or network error, the program will get stuck without any output, especially when users start the program, there is no error feedback.

Specifically, I suggested add a warning log when `ethclient.DialContext(ctx, url)` [failed](https://github.com/taikoxyz/taiko-client/blob/main/pkg/rpc/dial.go#L17).

**Comment by davidtaikocha** [comment]
Addressed in https://github.com/taikoxyz/taiko-client/pull/262 && https://github.com/taikoxyz/taiko-client/pull/263
