### ISSUE TITLE
Client makes taiko-geth lag to last verified block

### ISSUE THREAD

**Issue by leppaludi** [taikoxyz/taiko-client#291]
I updated to the latest taiko-client on git, commit https://github.com/taikoxyz/taiko-client/commit/949f376bc0e3772e8bd0ad3bad9ae5263c1b57b8 on branch `grimsvotn`

My node was then stuck on the "Last Verified Block" and didn't sync to the latest block on L2

Constant state of 30 minute lag. I reset the node and re-synced 4 times and it was consistent.

The logs from the execution engine (taiko-geth)

```
INFO [06-16|19:50:32.473] Imported new potential chain segment     number=195,809 hash=632700..400460 blocks=1    txs=1     mgas=0.128    elapsed="530.507µs" mgasps=240.986  age=30m8s     dirty=56.22MiB
INFO [06-16|19:50:32.473] Recovered head state                     number=195,809 hash=632700..400460
INFO [06-16|19:50:32.473] Extend chain                             add=10 number=195,809 hash=632700..400460
INFO [06-16|19:50:32.474] Chain head was updated                   number=195,809 hash=632700..400460
WARN [06-16|19:50:44.597] Ignoring already known beacon payload    number=195,809 hash=632700..400460 age=30m20s
WARN [06-16|19:50:56.718] Ignoring already known beacon payload    number=195,809 hash=632700..400460 age=30m32s
```

Meanwhile, the taiko-client had a lot of this in the logs

`unexpected ForkchoiceUpdate response status: VALID`

I rolled back to commit https://github.com/taikoxyz/taiko-client/commit/cb4dada3ef9d9cf673af20a942e6326ac7ed556b and then it synced right and everything worked.

**Comment by cyberhorsey** [comment]
Assigned to @davidtaikocha , think this PR introduced this bug: https://github.com/taikoxyz/taiko-client/commit/45d73b9da34232cf6a3c8636e97aef5854bb86bb
