### ISSUE TITLE
Contract accepts (Success) 2 x Prove Block tx for the same block from different provers

### ISSUE THREAD

**Issue by davaymne** [taikoxyz/taiko-client#302]
There are 2 x successful tx with `Prove Block` which are related to the same block `499890`:

https://sepolia.etherscan.io/tx/0xc37145560cd06d532a320ce7f7b23883915747deb725bc1ccf5b7985ec92f0a0
https://sepolia.etherscan.io/tx/0x28c1433271c1577a192288348488c6e63c4a7168cc5b06ba5b2eaeb7e60afb39 

The only one MUST be success.

**Comment by davaymne** [comment]
Update:

There is a block: https://sepolia.etherscan.io/txs?block=3805868, and taiko block: 506570
 - Tx 1 - failed , Position In Block: 22,
 - Tx 2 - success, Position In Block: 29,
 
 Why `Prove Block` tx with position 22 fails while position - 29 success?

**Comment by cyberhorsey** [comment]
> There are 2 x successful tx with `Prove Block` which are related to the same block `499890`:
> 
> https://sepolia.etherscan.io/tx/0xc37145560cd06d532a320ce7f7b23883915747deb725bc1ccf5b7985ec92f0a0 https://sepolia.etherscan.io/tx/0x28c1433271c1577a192288348488c6e63c4a7168cc5b06ba5b2eaeb7e60afb39
> 
> The only one MUST be success.

This is incorrect, as one is most likely proving a fork. ProveBlock can not be called to submit an identical proof for the same fork choice but can be called for different fork choices. If you are submitting proofs that do not revert and are proving an incorrect fork choice you need to resync your node and prover.

**Comment by davaymne** [comment]
yes, it is clear that provers can prove blocks from forks.

Having that there are 2 questions:

1. How prover would know that it is proving fork?
2. If they are proving fork, proof should be different, right? 

Below you can see 2 tx proving same block, with exact same `input`(proof) and both are success:
Block: 499906 (which is not %10 as per contract config is that a case?)
 - Position: 44 - [0xfb371f2771cc9aa57a17f6e89ba9f571db073cc52fd45724c5f0fac3e5f2b2ff](https://sepolia.etherscan.io/tx/0xfb371f2771cc9aa57a17f6e89ba9f571db073cc52fd45724c5f0fac3e5f2b2ff)
 - Position: 45 - [0xa1cc6a8034b45e33ee9d939ca551b55e7708fe1b650d976375ef7f79002f4d11](https://sepolia.etherscan.io/tx/0xa1cc6a8034b45e33ee9d939ca551b55e7708fe1b650d976375ef7f79002f4d11)

**Comment by davaymne** [comment]
Update:
in both transactions prover set to:
prover : [0x0000000000000000000000000000000000000001](https://sepolia.etherscan.io/address/0x0000000000000000000000000000000000000001)

Is that legitimate?

**Comment by davidtaikocha** [comment]
closed by https://github.com/taikoxyz/taiko-client/issues/304
