### ISSUE TITLE
gaxle pover and proposer quest

### ISSUE THREAD

**Issue by mgcnb666** [taikoxyz/taiko-client#323]
Can we create a website for pover and proposer node users to submit their Galxe task addresses? Since most node users are running on newly generated addresses on servers, would you use your main address to run on a centralized server? Obviously, we need a website that allows for custom submissions, and uses wallet signatures to determine the address ownership, so that node users can customize their own Galxe task addresses

**Comment by davidtaikocha** [comment]
I believe our `eventindexer` service is recording those addresses, at least for proposers / provers.
