### ISSUE TITLE
Prover could not start with local build with error: failed to get protocol configs: abi: improperly encoded uint8 value

### ISSUE THREAD

**Issue by davaymne** [taikoxyz/taiko-client#358]
current commit: ffe2f906808f99a48f6a848351c9a34ea63f02b7
golang: 1.21.0
**What:** prover could not start, fails with error ` failed to get protocol configs: abi: improperly encoded uint8 value`

Option 1 - local build
Local build by `make build` with `LD_FLAGS := -ldflags "$(LD_FLAGS_ARGS) -extldflags=-static"` in Makefile

Option 2 - docker image
Docker image `docker build `

It fails here: https://github.com/taikoxyz/taiko-client/blob/ffe2f906808f99a48f6a848351c9a34ea63f02b7/bindings/gen_taiko_l1.go#L444

**Comment by cyberhorsey** [comment]
You should be using the Grimsvotn branch for L2 and Eldfell for L3, main branch has changed not deployed to either testnet.
