### ISSUE TITLE
Can 'snapshots' or 'checkpoint files' be used to assist with client synchronization?

### ISSUE THREAD

**Issue by joohhnnn** [taikoxyz/taiko-client#365]
https://github.com/taikoxyz/taiko-client/blob/b6cd4db1cffd15f95f383b2c5058d1c95d30d473/bindings/gen_taiko_l1.go#L1315
I'm looking at how Driver assist with sync logic and noticed that key data is obtained by scanning logs during the OnBlocks callback. Can we use extra checkpoint file to associate the sync process？or we can explore a structure in the execution layer to store mainnet event information, and validate and share it through the p2p network? This might reduce dependence on mainnet RPC and increase synchronization speed (for clients syncing non-latest blocks). I'm not sure if this is appropriate, just brainstorming after browsing the code. If I'm misunderstanding something, please point it out.

**Comment by davidtaikocha** [comment]
Yes we have this kind of feature, plz check: 
- https://github.com/taikoxyz/taiko-client/blob/main/driver/chain_syncer/chain_syncer.go#L66
- https://github.com/taikoxyz/taiko-client/tree/main/driver/chain_syncer/beaconsync
