### ISSUE TITLE
Prover: stucks with no capacity

### ISSUE THREAD

**Issue by davaymne** [taikoxyz/taiko-client#401]
**What:** Prover gets stuck with "no capacity"
Prover: 0xfbfd4F6993BC0D3481B9bf61AD0892f817a2e7aC

**Background**
It has been working for a while and then at some time after successfull Proof:
```
INFO [09-21|02:53:28.264] Proof generated                          height=20650 degree=22 time=4m0.02887416s
INFO [09-21|02:53:28.264] New valid block proof                    blockID=20650 proposer=0x53bC9E660415632C1487Baf7d7f3725fB49870FA hash=9f8fc5..c8b999 proof=0000000000000000000000000000000098862a308e41d
```
It sends a message
```
ERROR[09-21|03:19:40.905] Handle new BlockProposed event error     error="no prover capacity available"
```
And begins:
```
INFO [09-21|03:19:49.866] Cancel proof generation for block        blockId=20588
INFO [09-21|03:19:49.866] Proposed block information               blockID=20588 prover=0xfbfd4F6993BC0D3481B9bf61AD0892f817a2e7aC proposedAt=1,695,264,012
INFO [09-21|03:19:49.866] Proposed block is provable               blockID=20588 prover=0xfbfd4F6993BC0D3481B9bf61AD0892f817a2e7aC proofWindowExpired=false
```
As per status it says:
```
{"minProofFee":10,"maxExpiry":3600,"currentCapacity":0}
```

While TTKOj token balance is enough.

**Workaround:**
It gets back to normal after restart.

**Comment by davidtaikocha** [comment]
Is `Cancel proof generation for block` log the reason? cc @cyberhorsey

**Comment by davaymne** [comment]
I dont know what is the reason... This is my current request for this.
But if it canceled, why it did not release capacity and keeps returning "currentCapacity":0 untill it restarts?

**Comment by davidtaikocha** [comment]
Opened a PR to try to fix this: https://github.com/taikoxyz/taiko-client/pull/402

**Comment by davaymne** [comment]
It happened again. 
Any logs needed?

**Comment by davaymne** [comment]
Could you pls clarify a case when "local proof generation can be canceled".
 - Proposer assigns proposed block for prover and no one can submit proof for current block unless time is expired, which is 5400 sec.
 
In the logs I dont see any proofs generating up to 5400 sec, in fact it was no more then 5 min
