### ISSUE TITLE
bug report: eth_syncing returns false when client is still syncing

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-client#537]
i noticed that when i call eth_syncing like this:

<img width="547" alt="image" src="https://github.com/taikoxyz/taiko-client/assets/13951458/8ed37cc2-159d-457c-ba2b-16573707d336">

even when the node is still syncing, it returns as false. previously it showed me it was syncing and returned the block info.

**Comment by davidtaikocha** [comment]
Emmm right now after a node starts syncing unverified blocks from L1 smart contract, it will return `false`.
