### ISSUE TITLE
bug report: archive node says not detected, but trying to fetch the block 0 works from cli

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-client#538]
i tried to fetch block 0 from `wss://ethereum-holesky.publicnode.com` to check if it is an archive endpoint. it worked and gave me the block details, but when i tried this endpoint in taiko-client, it would not sync and the logs say it is not an archive endpoint.

**Comment by davidtaikocha** [comment]
I think for non-archived node, u can still fetch the node info, but can't call `eth_getProof` at a relatively old height

**Comment by d1onys1us** [comment]
> I think for non-archived node, u can still fetch the node info, but can't call `eth_getProof` at a relatively old height

sounds good, this works well for the healthcheck that i need to do.
