### ISSUE TITLE
Prover is getting assigned to proposed blocks while it is getting catch up

### ISSUE THREAD

**Issue by davaymne** [taikoxyz/taiko-client#564]
### Describe the bug

Upon Prover start it takes up to an hour to catch up to the latest verified block.
While it is getting catch up it is still able to accept prover assignement request from Proposer and `proposeConcurrencyGuard` is not working.

It is very easy to drain whole prover balance TTKOT as per this issue.
See the screenshot
<img width="1144" alt="Screenshot 2024-02-23 at 01 01 51" src="https://github.com/taikoxyz/taiko-client/assets/29555611/60568ecb-9df2-4d88-aace-c0a69aa0f6c0">

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davaymne** [comment]
Update: it could potentially happed because prover had an issue to request raiko to generate prove

```
ERROR[02-23|00:36:33.406] Failed to request proof                  height=353,536 err="task 93 panicked" endpoint=http://x.x.x.x:8090
ERROR[02-23|00:36:43.631] Failed to request proof                  height=353,536 err="task 105 panicked" endpoint=http://x.x.x.x:8090
...
```

**Comment by davidtaikocha** [comment]
We just introduced a new refactor of Prover, and plan to release it in ~2 weeks, i think it will be fixed, feel free to reopen it if this issue still exists after the release :)
