### ISSUE TITLE
L2SuggestedFeeRecipient is not an available parameter in the .env

### ISSUE THREAD

**Issue by vijaypondini** [taikoxyz/taiko-client#579]
### Describe the bug

Description of the bug here.
Hello, the L2_SUGGESTED_FEE_RECIPIENT is not a parameter in the .env. We will need to add it!

### Steps to reproduce

Steps to reproduce here.
Check the .env , that variable doesn't exist! Need to update the .env

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-client/pull/550
