### ISSUE TITLE
Taiko NFT bridge solution 

### ISSUE THREAD

**Issue by jigarparmar519** [taikoxyz/taiko-client#592]
### Describe the feature request

Why we need the taiko NFT Bridge?
An NFT bridge is a helping hand used to connect different networks throughout the blockchain ecosystem. Most of the time, you need to send NFTs from one test network to another on the Ethereum platform. NFT bridging is a helpful solution when you want to send an Ethereum test token from taiko  katla(testnet) to another test network (Goerli).
Note that every network (katla, Goerli, matic, etc) has its own protocols. So, an NFT bridge solution must meet their requirements to establish a trustworthy connection between them.
We need NFT bridging in order to reach the following benefits:
Facilitating the transfer of NFTs between different networks on Ethereum
Making NFTs accessible everywhere
Accessing all the features of different networks

if its available in testnet then it will be really good for the tests as well

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Plz open these kind of issues here: https://github.com/taikoxyz/taiko-mono/issues :)
