### ISSUE TITLE
Failed to using P2P  sync where lastSyncedVerifiedBlockID==1 or LatestVerifiedHeight == 1 

### ISSUE THREAD

**Issue by alexshliu** [taikoxyz/taiko-client#68]
This happened when there was only one block to be verified on L1

![p2p-sync-failed](https://user-images.githubusercontent.com/104080237/206505080-0f62ffab-66bd-4d7e-8791-18d06328f90e.png)

**Comment by davidtaikocha** [comment]
@alexshliu is this fixed by https://github.com/taikoxyz/taiko-client/pull/83 ?

**Comment by alexshliu** [comment]
> @alexshliu is this fixed by #83 ?

yes
