### ISSUE TITLE
taiko-client /status endpoint runtime error: invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-client#767]
### Describe the bug

The /status endpoint of provers isn't working anymore this testnet. I tried with multiple prover IP addresses, see image for logs of the error
![image](https://github.com/taikoxyz/taiko-client/assets/60930264/4b0f73df-7f90-4fcd-a4d9-97b28743dc19)

### Steps to reproduce

1. visit `<prover IP address>:9876/status`
2. error appears

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by YoGhurt111** [comment]
Which way are you running taiko-node?  `stn` or `simple-taiko-node`?

**Comment by YoGhurt111** [comment]
You can run a prover with `simple-taiko-node`.
 https://docs.taiko.xyz/guides/enable-a-prover/

**Comment by wolfderechter** [comment]
> Which way are you running taiko-node? `stn` or `simple-taiko-node`?

I haven't been able to run a prover myself, but I think most of the provers are using `simple-taiko-node`. I need this `/status` endpoint to setup my prover marketplace.

Try for yourself with any prover IP address or one of the following from the discord:
    http://kenz-prover.hekla.kzvn.xyz:9876/status
    http://hekla.stonemac65.xyz:9876/status
    http://taiko.web3crypt.net:9876/status
    http://198.244.201.79:9876/status
    
Normally you should see a simple json with status values ( https://github.com/taikoxyz/taiko-client/blob/c421f0f4fbf55787bdaac7bfc4b7f11318f37d6d/prover/server/api.go#L44-L69 ) but something goes wrong and it errors `runtime error: invalid memory address or nil pointer deference` (see image) 

So this issue should remain open

**Comment by YoGhurt111** [comment]
@wolfderechter Thank you for taking the time to report this issue! Your feedback improves the quality of our project. We will fix it later and thanks again for your contribution!

**Comment by wolfderechter** [comment]
Thanks for the quick fix, I'm looking forward to see it released in the hekla testnet!

**Comment by d1onys1us** [comment]
@gitpoap-bot award @wolfderechter

**Comment by d1onys1us** [comment]
@gitpoap-bot award @wolfderechter
